### ISSUE TITLE
Error transpiling

### ISSUE THREAD

**Issue by tilk48** [chgibb/hydro-sdk#38]
Hi,

I set up a new, fresh project with the sdk installed but when I try to transpile a file I get this error:
`
  node node_modules/hydro-sdk/dist/compiler -t test.ts -m step -d Resources -p release
Build 50ccb822a6914211d435389f35ac1e505ba05ebc53fe191da432b907116ff047
Compiling  [█---------------------------------------] 2/113 dart/collection/list.ts(node:39005) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'fileName' of undefined
    at /Users/tilmankieselbach/Development/liquidcore_test/node_modules/hydro-sdk/dist/compiler/src/bundle/buildBundleInfo.js:153:74
    at step (/Users/tilmankieselbach/Development/liquidcore_test/node_modules/hydro-sdk/dist/compiler/src/bundle/buildBundleInfo.js:44:23)
    at Object.next (/Users/tilmankieselbach/Development/liquidcore_test/node_modules/hydro-sdk/dist/compiler/src/bundle/buildBundleInfo.js:25:53)
    at step (/Users/tilmankieselbach/Development/liquidcore_test/node_modules/hydro-sdk/dist/compiler/src/bundle/buildBundleInfo.js:29:139)
    at Object.next (/Users/tilmankieselbach/Development/liquidcore_test/node_modules/hydro-sdk/dist/compiler/src/bundle/buildBundleInfo.js:25:53)
    at fulfilled (/Users/tilmankieselbach/Development/liquidcore_test/node_modules/hydro-sdk/dist/compiler/src/bundle/buildBundleInfo.js:16:58)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processTimers (internal/timers.js:489:9)
(node:39005) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#)
(node:39005) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

The file is the hello-world.ts file from the example and the sdk worked yesterday on another project. Thanks for your time

**Comment by chgibb** [comment]
Thanks for taking interest and trying it out! I've reproduced exactly what you've described here. Looks like it's due to an assumption around use of the Typescript compiler API. It will take me some time to put together a fix and confirm that it is indeed fixed.

**Comment by chgibb** [comment]
@tilk48 #40 should have address the errors you're seeing here. Please let me know if it did!

**Comment by tilk48** [comment]
Can confirm to be fixed, thank you very much!
